#!/bin/bash
# A menu driven shell script sample template 
## ----------------------------------
# Step #1: Define variables
# ----------------------------------
EDITOR=vim
PASSWD=/etc/passwd
RED='\033[0;41;30m'
STD='\033[0;0;39m'
 
# ----------------------------------
# Step #2: User defined function
# ----------------------------------
pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}

one(){
	echo "nameserver 178.22.122.100" |tee /etc/resolv.conf
	echo "nameserver 185.51.200.2" |tee -a /etc/resolv.conf
	echo "nameserver 8.8.8.8" |tee -a /etc/resolv.conf
	echo "nameserver 194.5.206.38" |tee -a  /etc/resolv.conf
	sleep 5
	
}
 
# do something in two()
two(){
	sed -i 's/enforcing/disabled/g' /etc/selinux/config
	setenforce 0

}


three(){
        sed -i 's/enforcing/disabled/g' /etc/selinux/config
        setenforce 0

}


four(){
        sed -i 's/enforcing/disabled/g' /etc/selinux/config
        setenforce 0

}
 


# function to display menus
show_menus() {
	clear
	echo "~~~~~~~~~~~~~~~~~~~~~"	
	echo " M A I N - M E N U"
	echo "~~~~~~~~~~~~~~~~~~~~~"
	echo "1. Set DNS"
	echo "2. Disable Selinux"
	echo "3. Disable Selinux"
	echo "4. ADD nomodset"
	echo "5. Exit"
}
# read input from the keyboard and take a action
# invoke the one() when the user select 1 from the menu option.
# invoke the two() when the user select 2 from the menu option.
# Exit when user the user select 3 form the menu option.
read_options(){
	local choice
	read -p "Enter choice [ 1 - 3] " choice
	case $choice in
		1) one ;;
		2) two ;;
		3) threee ;;
		4) four ;;
		5) exit 0;;
		*) echo -e "${RED}Error...${STD}" && sleep 2
	esac
}
 
# ----------------------------------------------
# Step #3: Trap CTRL+C, CTRL+Z and quit singles
# ----------------------------------------------
trap '' SIGINT SIGQUIT SIGTSTP
 
# -----------------------------------
# Step #4: Main logic - infinite loop
# ------------------------------------
while true
do
 
	show_menus
	read_options
done
