global:
  resolve_timeout: 20s

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  reciver: 'web.hook'
recivers:
- name: 'web.hook'
  webhook_configs:
  - url: '--data "username=ts_monitor&password=Vqk6Dny(JM&to=09305372401&from=10004427&text=Alert test &isflash=false" https://rest.payamak-panel.com/api/SendSMS/SendSMS'
